version: '3.8'

services:
  backend:
    build: ./backend
    container_name: django_api
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - SECRET_KEY=dev-secret-key-123
      - ALLOWED_HOSTS=localhost,127.0.0.1,backend
    restart: unless-stopped

  frontend:
    build: ./frontend

    container_name: react_client

    volumes:
      - ./frontend:/app
      - /app/node_modules

    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://localhost:8000/api # Para desarrollo local
      # O usa esto para acceder desde el contenedor:
      # - VITE_API_URL=http://backend:8000/api
      - CHOKIDAR_USEPOLLING=true
    command: sh -c "npm install && npm run dev"
    depends_on:
      - backend
    restart: unless-stopped
